### ISSUE TITLE
Schematics app not found in @nrwl/workspace

### ISSUE THREAD

**Issue by faisal-zulfiqar** [onehungrymind/angular-core-workshop#10]
I started the course sometime ago and when following the command `ng new app` it said that schematic `app` was not found in `@nrwl/workspace`. I spent some time fixing things around and have reduced the solution to following steps:

1. Create the workspace using the following command:
`npx create-nx-workspace angular-core-workshop --preset=empty --cli=angular`

2. Change into the angular-core-workshop directory.
`cd angular-core-workshop`

3. Open `nx.json` file and replace `"npmScope"` property value to `"workshop"`

4. Run the following command:
`ng config schematics.@nrwl/schematics:component.styleext scss`

5. Run the following command:
`ng add @nrwl/angular`

6. Open `angular.json `and replace

```
"cli": {
    "defaultCollection": "@nrwl/workspace"
}
```

with

```
"cli": {
    "defaultCollection": "@nrwl/angular"
}
```

7. Use the following command to generate the dashboard application:

`ng g app dashboard --routing -p=app --style=scss --unit-test-runner=karma`

8. Run following commands:

```
npm install @ngrx/store --save
npm install @ngrx/router-store --save
npm install @ngrx/effects --save
```

9. Goto `app.module.ts `in dashboard application

Add this line at the top:

`import { NxModule } from '@nrwl/angular';
`
And then add the following line in the imports array:

`NxModule.forRoot()`

**Comment by Rotho98** [comment]
I can confirm this works on Ubuntu 18.04.1. Seems like the beginning of the course may be out of date with steps necessary to get to a working project

**Comment by aklukas** [comment]
README has been updated to resolve this issue.
