### ISSUE TITLE
create-nx-workspace: command not found

### ISSUE THREAD

**Issue by seeyijie** [onehungrymind/angular-core-workshop#5]
Installed globally with:
1) npm i -g @angular/cli
2) npm i -g @nrwl/schematics

I have tried deleting my node_modules globally but to no avail.

Current node version is v10.16.0

**Comment by 1Marc** [comment]
try running through npx

`npx create-nx-workspace myworkspace`

https://nx.dev/angular/getting-started/getting-started

**Comment by seeyijie** [comment]
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yijie/.npm/_logs/2019-07-10T00_17_32_810Z-debug.log
Install for create-nx-workspace@latest failed with code 1
yijie@yijie-ThinkPad-T480:~/Documents$ node -v
v10.16.0
yijie@yijie-ThinkPad-T480:~/Documents$ npm -v
6.9.0

I tried with "npm init nx-workspace myworkspace" too but to no avail and
get the same error.

**Comment by 1Marc** [comment]
Looks like your schematics module didnt install properly? 

please refer to their getting started guide https://nx.dev/angular/getting-started/getting-started and their community to get up and running. Your issue isn't with our course material, but the issue  is that for some reason their module isn't running properly on your machine.

**Comment by mburri** [comment]
while the the actual issue is in fact that " their module isn't running properly on [his] machine." it is also true that the project setup does not work with the instructions stated in the readme. 
The proper way to create the workspace seems to be to use npx...

**Comment by NinjaDexter123** [comment]
Found this set of commands on stakeOverflow answer. It saved the day again as I was facing the same issue. 
Apparently what it does is.
clears the npm cache forcefully.
reinstalls node
reinstalls npm in unsafe mode.

sudo rm -rf ~/.node-gyp
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo npm i --unsafe-perm

**Comment by ilyasKerbal** [comment]
Same issue
