### ISSUE TITLE
Document options when running create-nx-workspace

### ISSUE THREAD

**Issue by carl12** [onehungrymind/angular-core-workshop#7]
I am going through the setup as specified in this readme and after running `npx create-nx-workspace angular-core-workshop` I am asked a few questions. It would be nice to get some guidance about the answers to those questions. 

The first one asks what to create in the new workspace. I assumed that the type would be an Angular application, but it looks like a blank workspace is expected. Given that answer, I guessed that the cli would be the Angular CLI because it's what he's talking about in the videos

It would be nice if the correct options were specified.

**Comment by aklukas** [comment]
README has been updated to resolve this issue.
