### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz: ESOCKETTIMEDOUT".

### ISSUE THREAD

**Issue by Azghour-Saad** [onehungrymind/angular-core-workshop#8]
i'm doing all the step correctly 

but when i want to create a new Nx workspace by running :

**npx create-nx-workspace angular-core-workshop**

i'm getting this error, any help please **!!!**

![error](https://user-images.githubusercontent.com/33766249/66205301-fd49ad80-e6a4-11e9-9c6e-e782a716ddec.jpg)

**Comment by aklukas** [comment]
@Azghour-Saad have you resolved this?

**Comment by Azghour-Saad** [comment]
@aklukas Yes, by running VS Code as administrator  💯 💯
